// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvd1wNAcZcMipkEUs3zbWNMIGvUVZQZY',
    appId: '1:504659949155:web:cf2750f8f792337c462a56',
    messagingSenderId: '504659949155',
    projectId: 'madinclass14',
    authDomain: 'madinclass14.firebaseapp.com',
    storageBucket: 'madinclass14.firebasestorage.app',
    measurementId: 'G-FF460GGKTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMchsPcAOGO7qrHeQbtMxFsIFZh2CiMcw',
    appId: '1:504659949155:android:b500141bb025430f462a56',
    messagingSenderId: '504659949155',
    projectId: 'madinclass14',
    storageBucket: 'madinclass14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0fDGTjZ3jDK2-CVO9CYAjdJyYanH7cU',
    appId: '1:504659949155:ios:0e1d8094e3143603462a56',
    messagingSenderId: '504659949155',
    projectId: 'madinclass14',
    storageBucket: 'madinclass14.firebasestorage.app',
    iosBundleId: 'com.example.madInclass14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0fDGTjZ3jDK2-CVO9CYAjdJyYanH7cU',
    appId: '1:504659949155:ios:0e1d8094e3143603462a56',
    messagingSenderId: '504659949155',
    projectId: 'madinclass14',
    storageBucket: 'madinclass14.firebasestorage.app',
    iosBundleId: 'com.example.madInclass14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUvd1wNAcZcMipkEUs3zbWNMIGvUVZQZY',
    appId: '1:504659949155:web:347cdf6c4f77eb36462a56',
    messagingSenderId: '504659949155',
    projectId: 'madinclass14',
    authDomain: 'madinclass14.firebaseapp.com',
    storageBucket: 'madinclass14.firebasestorage.app',
    measurementId: 'G-08NMK3YZKJ',
  );
}
